#!/bin/bash
# vcpkg-licenses.sh
# Usage: ./vcpkg-licenses.sh [triplet] [vcpkg-root]
# ./vcpkg-licenses.sh vcpkg ./vcpkg_installed/x64-linux/share ~/Projects/vcpkg/vcpkg
# x64-linux - depends of OS of machine
# ~/Projects/vcpkg/vcpkg - path to vcpkg installation (~/Projects/vcpkg/vcpkg/ports needs to exist)

# ! generated by claudeAI, use on your own risk

TRIPLET=${1:-vcpkg} # use 
INSTALLED_DIR=${2:-./vcpkg_installed/$TRIPLET/share}
VCPKG_ROOT=${3:-${VCPKG_ROOT:-$HOME/vcpkg}}
PORTS="$VCPKG_ROOT/ports"

printf "%-30s %-15s %-15s %s\n" "Package" "Version" "License" "HomePage"
printf "%-30s %-15s %-15s %s\n" "-------" "-------" "-------" "-------"

for dir in "$INSTALLED_DIR"/*/; do
    pkg=$(basename "$dir")
    # echo "DEBUG: processing $pkg"
    [[ "$pkg" == vcpkg-* ]] && continue
    version=$(jq -r '.version // .["version-string"] // .["version-semver"] // "unknown"' "$PORTS/$pkg/vcpkg.json" 2>/dev/null)
    license=$(jq -r '.license // "unknown"' "$PORTS/$pkg/vcpkg.json" 2>/dev/null)
    homepage=$(jq -r '.homepage // "unknown"' "$PORTS/$pkg/vcpkg.json" 2>/dev/null)
    printf "%-30s %-15s %-15s %s\n" "$pkg" "$version" "$license" "$homepage"
done