name: Build installer

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-2022
    permissions:
      contents: read
      packages: read
    env:
      NUGET_GITHUB_USER: ${{ github.actor }}
      NUGET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup listener environment
        uses: ./.github/actions/listener-preparation

      - name: Build listener DLL
        run: just listener-build

      - name: Publish sender
        run: just sender-publish
        env:
          Platform: ""

      - name: Publish sender.DPAPI
        run: just sender-libs-build

      - name: Build installer
        run: just build-installer

      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: bin\x64\Release\Installer.msi
