name: Build installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-2022
    permissions:
      contents: write # because of releasing the MSI
      packages: read
    env:
      NUGET_GITHUB_USER: ${{ vars.NUGET_GITHUB_USER }}
      NUGET_GITHUB_TOKEN: ${{ secrets.NUGET_GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup listener environment
        uses: ./.github/actions/listener-preparation

      - name: Build listener DLL
        run: just listener-build

      - name: Publish sender
        run: just sender-publish
        env:
          Platform: ""

      - name: Publish sender.DPAPI
        run: just sender-libs-build

      - name: Build installer
        run: just build-installer

      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: bin\x64\Release\Installer.msi

      - name: Create GitHub Release and upload MSI
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/x64/Release/Installer.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
